### ISSUE TITLE
.Bold case in FontWeight enum?

### ISSUE THREAD

**Issue by jedmund** [adamyanalunas/Font#5]
Is there any reason this isn't here? 

The weight I'm using isn't Semi-Bold, I also use Black, and the semantics are killing me.

Thanks!

**Comment by adamyanalunas** [comment]
My logic was based off the weight naming that I've seen in fonts I commonly use. No particular reason not to include the generic “bold”. 

I tried to make Font open enough so that each family could define its own weighting conversions as needed. I'm open to a PR that includes bold, if you want.

**Comment by adamyanalunas** [comment]
I snuck in `.bold` while I was working on #7. Hopefully this addresses your need. Let me know if it's not quite right.
